### ISSUE TITLE
Category with many spaces in the title doesn't display correctly

### ISSUE THREAD

**Issue by Vetgam** [levelupik/levelupik#16] opened 2020-05-22 13:42 UTC
**Steps to reproduce**:
Create a new category with many spaces in the title. For example "Something       like         that".
Pay attention to the created category title.
Click on the created category then click on the button "edit".
Pay attention to how the category name truly displays.
![weirdNoteTitleLogic](https://user-images.githubusercontent.com/44175945/82673802-0d6dc780-9c4b-11ea-9578-03d91a321f4d.gif)

**Actual result**:
There is a mismatch between how the user named his category and how it displays.

**Expected result**:
There is shouldn't be a mismatch

**Comment by levelupik** [comment] 2020-05-22 18:59
Thank you, for your request.
It is a bug.
Of course the content of the category should look the same on editing and on view.

It will be fixed in the next releases.

**Comment by ritostopher** [comment] 2020-06-17 20:27
The issue is fixed on v0.4, it is should look the same now.

**Comment by levelupik** [comment] 2020-06-17 20:29
The issue is fixed on v0.4, it is should look the same now.

**Closed as completed** 2020-06-17 20:29 UTC
Labels: bug, enhancement

**Comment by ViktoriaNeva** [comment] 2020-07-21 00:16
@levelupik @Vetgam 
After fixing this issue - preview has a problem with displaying enter.
![2020-07-21_02-59-36](https://user-images.githubusercontent.com/5111608/87998444-9fd20080-cb00-11ea-9dca-9678f6c4d63c.png)
